### ISSUE TITLE
Increment/Decrement $currentvalue

### ISSUE THREAD

**Issue by atchoo78** [terlan98/CircularSlider#1]
Hi,

Thanks for making this slider. I am currently trying to add increment (+) and decrement (-) buttons to my SwiftUI view, so the user can (optionally) select numbers from minValue to maxValue with more precision than dragging/moving the knob/slider. 

I’m able to make the value/number change (and the track fill color), but I don’t understand how to programatically move the knob and update the UI accordingly. Do you have any suggestions?

Thanks. Much appreciated! ✨

Andreas

**Comment by terlan98** [comment]
Hi Andreas,

In order to move the knob, the `angle` variable must be updated by calling `valueToAngle(value: currentValue)` method. Please try and let me know if it works.

**Comment by atchoo78** [comment]
> Hi Andreas,
> 
> 
> 
> In order to move the knob, the `angle` variable must be updated by calling `valueToAngle(value: currentValue)` method. Please try and let me know if it works. 

Thanks! I tried, but I just don't know how to reach that function/variables from outside the CircularSlider class (ie. from my content view, where everything is wrappers 🤷🏻‍♂️). I'm kinda new to SwiftUi although I have programmed in Swift for some time.

**Comment by atchoo78** [comment]
@terlan98 I’ve managed to get/print the angle and all the values (newValue, % and currentValue), but I can’t figure out how to actually make the knob/vector move 😓

**Comment by terlan98** [comment]
@atchoo78 I added a new commit that makes updating the value externally easier. Just change the value that you have passed to CircularSlider and it will adjust the knob position automatically.

**Comment by atchoo78** [comment]
Wow..that’s awesome 😀 Great!
