### ISSUE TITLE
Slider .onChange()

### ISSUE THREAD

**Issue by alantrundle** [terlan98/CircularSlider#4]
Hi Tarlan,

is it possible to implement an onChange event, like on touch down, or on touch up, so that code can be run when the value is changed?

I tried to add .onChange() however this didn’t work in my content view.

or

It possible to add a function that runs on the content view when the slider changes?
I can then use code to work out which slider was changed.

I’m trying to make a Bluetooth app to control RGB LED’s, and as such need sliders to set the RGB values

thank you

**Comment by terlan98** [comment]
Hi Alan, 

Thank you for creating this issue. Have you tried passing your `@State` variable to the `onChange(of:initial:_:)` modifier on your SwiftUI View?

I mean something like this:

```swift
struct YourContentView: View {
    @State var value = 50.0

    var body: some View {
        VStack {
            CircularSlider(currentValue: $value)
        }
        .onChange(of: value) {
            print("Value changed! 🎉")
        }
    }
}
```

If this doesn't work, please let me know, and I'll see if I can come up with a different solution in a few days.

**Comment by alantrundle** [comment]
Hi Tarlan,

I didn’t even you you could do that !
I’m just off to to get some lunch with a friend, and I’ll jump straight on, and try it.

My MacBook packed up a few weeks ago, so I’m struggling with Xcode running on a Senoma VMware virtualised environment on my windows PC.
It’s pretty laggy to say the least.

Patience is a virtue.

I’ll get back to you later.

Thanks very much for getting in touch, I have to say your control is far superior to anything else available out there 🙏🙏👍🏼

Regards

Alan

Sent from my iPad

On 8 Feb 2024, at 11:23, Tarlan Ismayilsoy ***@***.***> wrote:

﻿

Hi Alan,

Thank you for creating this issue. Have you tried passing your @State variable to the onChange(of:initial:_:) modifier on your SwiftUI View?

I mean something like this:

struct YourContentView: View {
    @State var value = 50.0

    var body: some View {
        VStack {
            CircularSlider(currentValue: $value)
        }
        .onChange(of: value) {
            print("Value changed! 🎉")
        }
    }
}

If this doesn't work, please let me know, and I'll see if I can come up with a different solution in a few days.

**Comment by alantrundle** [comment]
Hi Tarlan,

Well it might have worked, except that my target OS is 16.7, since the iPad I’m using has just lapsed it’s upgradability, so I’m stuck with 16.7 for now, and the onChange you mentioned is only available on IOS 17.0 or newer.

Due to doing CoreBluetooth stuff, I have to test run my apps on a real device.

Another solution would be nice

[image0.jpeg]

Regards

Alan

Sent from my iPad

On 8 Feb 2024, at 12:33, Alan Trundle ***@***.***> wrote:

﻿ Hi Tarlan,

I didn’t even you you could do that !
I’m just off to to get some lunch with a friend, and I’ll jump straight on, and try it.

My MacBook packed up a few weeks ago, so I’m struggling with Xcode running on a Senoma VMware virtualised environment on my windows PC.
It’s pretty laggy to say the least.

Patience is a virtue.

I’ll get back to you later.

Thanks very much for getting in touch, I have to say your control is far superior to anything else available out there 🙏🙏👍🏼

Regards

Alan

Sent from my iPad

On 8 Feb 2024, at 11:23, Tarlan Ismayilsoy ***@***.***> wrote:

﻿

Hi Alan,

Thank you for creating this issue. Have you tried passing your @State variable to the onChange(of:initial:_:) modifier on your SwiftUI View?

I mean something like this:

struct YourContentView: View {
    @State var value = 50.0

    var body: some View {
        VStack {
            CircularSlider(currentValue: $value)
        }
        .onChange(of: value) {
            print("Value changed! 🎉")
        }
    }
}

If this doesn't work, please let me know, and I'll see if I can come up with a different solution in a few days.

**Comment by alantrundle** [comment]
Hi Tarlan,

After some googling, manged to get the code you sent to work.

            CircularSlider(currentValue: $greenVal, maxValue: 255.00)
                .onChange(of: greenVal, perform: { newvalue in

                    RGBColour = Color(red: redVal / 255, green: newvalue / 255, blue: blueVal / 255)

                    let msg = String(format: "%i,%i,%i,0", Int(redVal.rounded()), Int(newvalue.rounded()), Int(blueVal.rounded()))
                    print("Updated RGB Values \(msg)")

                    service.write(value: msg)
            })


The only trouble is, is that my ESP32 (BT receiving device) is having trouble keeping up with the amount of data that is being sent to it, on the fly while moving the slider.
hundreds of transmit's every second

service.write(value: msg)

Is there anyway to implement an onTouchUp event, or similar, so that data only gets sent when the user releases there finger from the slider?

I am setting a rectangle on the IOS application, so that the colour is displayed as the Slider(s) are being moved, and then when the user is happy, then he/she lifts there finger off the control, and it sends 1 RGB value (R,G,B) to my ESP32 RGB LED device.

Thanks

Alan

**Comment by terlan98** [comment]
Hi Alan,

Sure, I can implement a callback that is called when the user releases their finger. It'll take 2-3 days, though, as I'm a bit busy with some work-related stuff. I'll let you know when it's done 🙏

**Comment by alantrundle** [comment]
Thank you Tarlan - superstar 😇

Regards

Alan

Sent from my iPad

On 9 Feb 2024, at 12:41, Tarlan Ismayilsoy ***@***.***> wrote:

﻿

Hi Alan,

Sure, I can implement a callback that is called when the user releases their finger. It'll take 2-3 days, though, as I'm a bit busy with some work-related stuff. I'll let you know when it's done 🙏

**Comment by alantrundle** [comment]
Hi Tarlan,

Learning swift is very difficult, when compared to Cocoa (obj-c), however I am making progress.

[image0.png]



[image1.jpeg]

This ESP32 is running a Bluetooth 4.0 stack, and it receives data from my app as a CSV RGB value, and then displays it on my neoPixel LED

Coding is achieved using the Arduino IDE, Arduino compatible, however this microcontroller is much superior

Dual core 240Mhz
8MB RAM
8MB FLASH
Onboard BT and WiFi
Onboard WS2812B NeoPixel RGB LED
Tons of I/O

The LED is displaying this colour, at time of screenshot

Great little microcontroller for developing CoreBluetooth applications.
I saw your university page, so I thought you might be interested

Red 85
Green 82
Blue 124

It would be super good to only send a single CSV when somebody touches up on the knob.

No worries take your time. I very do appreciate your effort on this control, and it looks really good, and super easy to integrate, and ultimately use.


Thanks

Alan

Sent from my iPad

On 9 Feb 2024, at 12:52, Alan Trundle ***@***.***> wrote:

﻿ Thank you Tarlan - superstar 😇

Regards

Alan

Sent from my iPad

On 9 Feb 2024, at 12:41, Tarlan Ismayilsoy ***@***.***> wrote:

﻿

Hi Alan,

Sure, I can implement a callback that is called when the user releases their finger. It'll take 2-3 days, though, as I'm a bit busy with some work-related stuff. I'll let you know when it's done 🙏

**Comment by terlan98** [comment]
Hi Alan,

I'm glad to hear you're making progress with Swift :) The images can't be loaded for some reason but the project still sounds interesting.

I found some free time today (unexpectedly) and decided to implement the callback. You can find it on the latest release (1.1.0).

Here's a snippet illustrating how the callback can be used:

```swift
    CircularSlider(currentValue: $value) { selectedValue in
        print("Selected value: \(selectedValue)")
    }
```

In this example, the print statement is called only when the selection is finished (the user has released the knob)

I hope that makes it easier to integrate CircularSlider into your project. 

Best,
Tarlan
